### PR TITLE
Adding support for Node dependencies 

### PR DESCRIPTION
**Pull request by nicolasgarnier**
and config files for a few Firebase samples repos.

### CODE REVIEW

**Comment by nicolasgarnier** [comment]
@tswast PTAL! :)

**Comment by nicolasgarnier** [comment]
@ulukaya @samtstern FYI

**Comment by samtstern** [comment]
Wooooot

**Comment by nicolasgarnier** [comment]
How do we have this running on the 3 repos that I have provided the config for? I haven't received any Pull Request from the bot yet so I'm guessing there are some additional setup steps.

**Comment by tswast** [comment]
You also need to create a Kokoro config in the devrel folder on google3. go/dpebot has the full instructions.

**Comment by nicolasgarnier** [comment]
I don't have access to go/dpebot (yet at least, I've requested to be added) any pointers in the mean time? :)

**Comment by nicolasgarnier** [comment]
Done! CL sent.

**Pull request merged**
