### PR TITLE
Adds php update script

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tswast** [comment]
Ooh, thanks Brent! I've wanted this for as long as dpebot has been around. Thank you for working on it.

**Comment by tswast** [comment]
Approved, but looks like there's a few shell check style issues to cleanup.

**Comment by tswast** [comment]
Love it. Did the arrays trick work? I see a PR! https://github.com/GoogleCloudPlatform/php-docs-samples/pull/874 🎉

**Comment by bshaffer** [comment]
@tswast The array trick worked beautifully!

**Pull request merged**
