### PR TITLE
Android build tools 27.0.2 --> 27.0.3

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by nicolasgarnier** [comment]
Maybe you should have a bot that automates this PR

[insert Inception meme]

**Comment by samtstern** [comment]
I actually don't know of a good way to automate this since I purposely don't want to take the latest.  I am making an editorial decision about what build tools the Firebase samples should use.

For instance 28.x is out now but that's a bit too new for most devs and may cause some build errors for them.

**Comment by samtstern** [comment]
@tswast SGTM!

**Comment by samtstern** [comment]
The build failure is strange and may be solved by a restart:
```
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Ign:1 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Get:3 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release [2,495 B]
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease
Ign:5 http://mirror.jmu.edu/pub/ubuntu trusty InRelease
Get:6 http://mirror.jmu.edu/pub/ubuntu trusty-updates InRelease [65.9 kB]
Get:7 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release.gpg [801 B]
Ign:2 http://toolbelt.heroku.com/ubuntu ./ InRelease
Get:8 http://ftp.us.debian.org/debian unstable InRelease [233 kB]
Hit:9 http://toolbelt.heroku.com/ubuntu ./ Release
Get:10 http://mirror.jmu.edu/pub/ubuntu trusty-backports InRelease [65.9 kB]
Get:11 http://mirror.jmu.edu/pub/ubuntu trusty-security InRelease [65.9 kB]
Get:12 http://dl.google.com/linux/chrome/deb stable Release [1,189 B]
Get:13 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease [15.4 kB]
Get:14 http://dl.google.com/linux/chrome/deb stable Release.gpg [819 B]
Get:15 http://mirror.jmu.edu/pub/ubuntu trusty Release [58.5 kB]
Get:16 http://mirror.jmu.edu/pub/ubuntu trusty Release.gpg [933 B]
Get:17 https://dl.hhvm.com/ubuntu trusty InRelease
Get:18 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4/multiverse amd64 Packages [11.8 kB]
Get:19 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease [61.4 kB]
Get:20 http://mirror.jmu.edu/pub/ubuntu trusty-updates/universe Sources [259 kB]
Ign:21 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Get:22 http://mirror.jmu.edu/pub/ubuntu trusty-updates/main amd64 Packages [1,360 kB]
Get:24 http://mirror.jmu.edu/pub/ubuntu trusty-updates/main i386 Packages [1,285 kB]
Get:25 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease [15.4 kB]
Get:26 http://mirror.jmu.edu/pub/ubuntu trusty-updates/restricted amd64 Packages [21.4 kB]
Get:27 http://mirror.jmu.edu/pub/ubuntu trusty-updates/restricted i386 Packages [21.1 kB]
Get:28 http://mirror.jmu.edu/pub/ubuntu trusty-updates/universe amd64 Packages [601 kB]
Get:29 http://mirror.jmu.edu/pub/ubuntu trusty-updates/universe i386 Packages [589 kB]
Get:30 http://mirror.jmu.edu/pub/ubuntu trusty-updates/multiverse amd64 Packages [16.0 kB]
Get:31 http://mirror.jmu.edu/pub/ubuntu trusty-updates/multiverse i386 Packages [16.5 kB]
Get:32 http://mirror.jmu.edu/pub/ubuntu trusty-backports/main amd64 Packages [14.7 kB]
Get:33 http://mirror.jmu.edu/pub/ubuntu trusty-backports/main i386 Packages [14.7 kB]
Get:34 http://mirror.jmu.edu/pub/ubuntu trusty-backports/restricted amd64 Packages [40 B]
Get:35 http://mirror.jmu.edu/pub/ubuntu trusty-backports/restricted i386 Packages [40 B]
Get:36 http://mirror.jmu.edu/pub/ubuntu trusty-backports/universe amd64 Packages [52.5 kB]
Get:37 http://mirror.jmu.edu/pub/ubuntu trusty-backports/universe i386 Packages [52.4 kB]
Get:38 http://mirror.jmu.edu/pub/ubuntu trusty-backports/multiverse amd64 Packages [1,392 B]
Get:39 http://mirror.jmu.edu/pub/ubuntu trusty-backports/multiverse i386 Packages [1,376 B]
Get:40 http://mirror.jmu.edu/pub/ubuntu trusty-security/universe Sources [95.2 kB]
Get:41 http://mirror.jmu.edu/pub/ubuntu trusty-security/main amd64 Packages [941 kB]
Get:42 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease [15.4 kB]
Get:43 http://mirror.jmu.edu/pub/ubuntu trusty-security/main i386 Packages [869 kB]
Get:44 http://ftp.us.debian.org/debian unstable/main amd64 Packages [11.0 MB]
Get:45 http://mirror.jmu.edu/pub/ubuntu trusty-security/restricted amd64 Packages [18.1 kB]
Get:46 http://mirror.jmu.edu/pub/ubuntu trusty-security/restricted i386 Packages [17.8 kB]
Get:47 http://mirror.jmu.edu/pub/ubuntu trusty-security/universe amd64 Packages [306 kB]
Get:48 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,113 B]
Get:49 http://mirror.jmu.edu/pub/ubuntu trusty-security/universe i386 Packages [294 kB]
Get:50 http://mirror.jmu.edu/pub/ubuntu trusty-security/multiverse amd64 Packages [4,727 B]
Get:51 http://mirror.jmu.edu/pub/ubuntu trusty-security/multiverse i386 Packages [4,878 B]
Get:52 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease [15.4 kB]
Get:53 http://mirror.jmu.edu/pub/ubuntu trusty/universe Sources [7,926 kB]
Get:54 https://dl.hhvm.com/ubuntu trusty/main amd64 Packages [1,816 B]
Get:55 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease [15.5 kB]
Get:56 http://ftp.us.debian.org/debian unstable/main i386 Packages [11.0 MB]
Hit:57 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release
Get:58 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main amd64 Packages [190 kB]
Get:59 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main amd64 Packages [1,710 B]
Get:60 http://ftp.us.debian.org/debian unstable/contrib amd64 Packages [76.8 kB]
Get:61 http://ftp.us.debian.org/debian unstable/contrib i386 Packages [71.3 kB]
Get:62 http://ftp.us.debian.org/debian unstable/non-free amd64 Packages [109 kB]
Get:63 http://ftp.us.debian.org/debian unstable/non-free i386 Packages [97.0 kB]
Hit:64 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease
Get:65 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages [1,702 B]
Get:66 http://mirror.jmu.edu/pub/ubuntu trusty/main amd64 Packages [1,743 kB]
Get:67 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main amd64 Packages [3,482 B]
Get:69 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [189 kB]
Get:70 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages [3,482 B]
Get:71 http://mirror.jmu.edu/pub/ubuntu trusty/main i386 Packages [1,739 kB]
Get:73 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main amd64 Packages [7,494 B]
Get:74 http://mirror.jmu.edu/pub/ubuntu trusty/restricted amd64 Packages [16.0 kB]
Get:75 http://mirror.jmu.edu/pub/ubuntu trusty/restricted i386 Packages [16.4 kB]
Get:76 http://mirror.jmu.edu/pub/ubuntu trusty/universe amd64 Packages [7,589 kB]
Get:78 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages [7,640 B]
Get:79 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main amd64 Packages [430 B]
Get:80 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages [430 B]
Get:81 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main amd64 Packages [1,551 B]
Get:83 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages [1,551 B]
Get:84 http://mirror.jmu.edu/pub/ubuntu trusty/universe i386 Packages [7,597 kB]
Get:88 http://mirror.jmu.edu/pub/ubuntu trusty/multiverse amd64 Packages [169 kB]
Get:89 http://mirror.jmu.edu/pub/ubuntu trusty/multiverse i386 Packages [172 kB]
Get:90 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]
Reading package lists...
W: There is no public key available for the following key IDs:
7638D0442B90D010
E: Invalid message from method gpgv:  NO_PUBKEY 04EE7237B7D453EC
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $TRAVIS_APT_OPTS install shellcheck" failed and exited with 100 during .
```

**Pull request merged**
